title: Status Bar  # Empty
app:
  id: status.bar    # Status bar
  text_multithreading: true   # false
  antialiasing: true    # false
  try_opengles_first: true    # false
window:
  size: [480, 37]  # [1024, 768]
  position: [0, 0]  # [0, 0]
  min_size: [480, 40]  # None
  max_size: null    # None
  visible: true   # true
  resizable: true   # true
  decorations: true   # true
  transparent: true    # false
  always_on_top: false    # false
  icon_path: null # Todo
css:
  default: /etc/mecha-launcher-assets/status_bar/assets/css/style.css
layout:
  left: ["clock"]
  center: ["window_title"]
  right: ["wifi", "bluetooth", "battery",]
modules:
  clock:
    format: "%I:%M %p" # https://docs.rs/chrono/latest/chrono/format/strftime/index.html
  bluetooth:
    icon:
      on: /etc/mecha-launcher-assets/status_bar/assets/pngs/bluetooth_on.png"
      off: /etc/mecha-launcher-assets/status_bar/assets/pngs/bluetooth_off.png
      connected: /etc/mecha-launcher-assets/status_bar/assets/pngs/bluetooth_connected.png
  wifi:
    icon:
      off: /etc/mecha-launcher-assets/status_bar/assets/pngs/wifi_off.png
      on: /etc/mecha-launcher-assets/status_bar/assets/pngs/wifi_on.png
      low: /etc/mecha-launcher-assets/status_bar/assets/pngs/wifi_low.png
      weak: /etc/mecha-launcher-assets/status_bar/assets/pngs/wifi_weak.png
      good: /etc/mecha-launcher-assets/status_bar/assets/pngs/wifi_good.png
      strong: /etc/mecha-launcher-assets/status_bar/assets/pngs/wifi_strong.png
  battery:
    icon:
      level_100: /etc/mecha-launcher-assets/status_bar/assets/pngs/battery_100.png
      level_90: /etc/mecha-launcher-assets/status_bar/assets/pngs/battery_90.png
      level_80: /etc/mecha-launcher-assets/status_bar/assets/pngs/battery_80.png
      level_70: /etc/mecha-launcher-assets/status_bar/assets/pngs/battery_70.png
      level_60: /etc/mecha-launcher-assets/status_bar/assets/pngs/battery_60.png
      level_50: /etc/mecha-launcher-assets/status_bar/assets/pngs/battery_50.png
      level_40: /etc/mecha-launcher-assets/status_bar/assets/pngs/battery_40.png
      level_30: /etc/mecha-launcher-assets/status_bar/assets/pngs/battery_30.png
      level_20: /etc/mecha-launcher-assets/status_bar/assets/pngs/battery_20.png
      level_10: /etc/mecha-launcher-assets/status_bar/assets/pngs/battery_10.png
      level_0: /etc/mecha-launcher-assets/status_bar/assets/pngs/battery_0.png
